chore: testing ci/cd

diff --git a/.github/workflows/integration.yml b/.github/workflows/integration.yml
--- a/.github/workflows/integration.yml
+++ b/.github/workflows/integration.yml
@@ -1,6 +1,3 @@
-# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
-# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs
-# See supported Node.js release schedule at https://nodejs.org/en/about/releases/
 
 name: Integration Workflow
 
@@ -16,7 +13,7 @@ jobs:
 
     strategy:
       matrix:
-        node-version: [16.x, 18.x]
+        node-version: [20]
 
     steps:
     - name: Checkout repository
@@ -26,7 +23,6 @@ jobs:
       uses: actions/setup-node@v3
       with:
         node-version: ${{ matrix.node-version }}
-        cache: 'yarn'
 
     - name: Install dependencies
       run: yarn install
@@ -37,46 +33,47 @@ jobs:
     - name: Build
       run: yarn build
 
-#    - name: Run tests
-#      run: yarn test
-  # Deploy-Preview:
-  #   name: Deploy Preview
 
-  #   runs-on: ubuntu-latest
-  #   needs: ['build']
-  #   steps:
-  #     - name: Checkout repository
-  #       uses: actions/checkout@v2
+  Deploy-Preview:
+    name: Deploy Preview
 
-  #     - name: Cache Node.js modules
-  #       uses: actions/cache@v3
-  #       with:
-  #         path: |
-  #           ~/.yarn
-  #           ~/.cache
-  #           /www/wwwroot/CLIENTS/eu-africa-client/node_modules
-  #         key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
-  #         restore-keys: |
-  #           ${{ runner.os }}-node-
+    runs-on: ubuntu-latest
+    needs: ['build']
+    steps:
+      - name: Checkout repository
+        uses: actions/checkout@v2
 
-  #     - name: Install Node.js
-  #       uses: actions/setup-node@v3
-  #       with:
-  #         node-version: '16' 
+      - name: Install Node.js
+        uses: actions/setup-node@v3
+        with:
+          node-version: '20' 
 
-  #     - name: Set up SSH connection
-  #       uses: appleboy/ssh-action@master
-  #       with:
-  #         host: ${{ secrets.SERVER_IP }}
-  #         username: ${{ secrets.USER_NAME }}
-  #         passphrase: ${{ secrets.PASSWORD }}
-  #         key: ${{ secrets.SERVER_SSH_KEY }}
-  #         port: ${{ secrets.PORT }}
-  #         script: |
-  #           export PATH=$PATH:/www/server/nodejs/v14.17.6/bin
-  #           cd /www/wwwroot/CLIENTS/eu-africa-client
-  #           git pull origin main
-  #           yarn install --frozen-lockfile
-  #           yarn run build
-  #           pm2 start yarn --name eu-africa-client --start
-  #           pm2 startup
+      - name: Set up SSH connection
+        uses: appleboy/ssh-action@master
+        with:
+          host: ${{ secrets.SERVER_IP }}
+          username: ${{ secrets.USER_NAME }}
+          passphrase: ${{ secrets.PASSWORD }}
+          key: ${{ secrets.SERVER_SSH_KEY }}
+          port: ${{ secrets.PORT }}
+          script: |
+            set -e
+            echo "Changing directory to /www/wwwroot/CLIENTS/euclient"
+            if ! cd /www/wwwroot/CLIENTS/euclient; then
+               echo "Failed to change directory"
+               exit 1
+            fi
+            echo "Pulling latest code from origin/main"
+            if ! git pull origin main; then
+               echo "Failed to pull latest codes"
+               exit 1
+            fi
+            echo "Install Dependencies"
+            if ! yarn install; then
+               echo "Failed to Install dependencies"
+               exit 1
+            fi
+            echo "successfully Pulled"
+            # yarn run build
+            # pm2 start yarn --name eu-africa-client --start
+            # pm2 startup
